logging:
  level:
    com.smartguys: DEBUG
    org.springframework.data.mongodb: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.15:27017/mediclinic?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.9
