spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/mediclinic

server:
  port: 8080

cors:
  allowed-origins: http://localhost:3000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
